### ISSUE TITLE
Not sure why it isn't working as I do have the mapset that it is looking for?

### ISSUE THREAD

**Issue by A-WaZeD** [uyitroa/osr2mp4-app#103]
FileNotFoundError(2, 'No such file or directory')[Errno 2] No such file or directory: 'C:/Program Files (x86)/osu!/Songs/984684 Victorious Cast - Take a Hint feat Victoria Justice & Elizabeth Gillies (Speed Up Ver)\\Victorious Cast - Take a Hint feat. Victoria Justice & Elizabeth Gillies (Speed Up Ver.) (SquareTude) [I Think You Could Use a Mint].osu' Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 50, in run
    converter = Osr2mp4(filedata=config, filesettings=settings, filepp=ppsettings, logtofile=True, logpath=logpath)
  File "C:\Users\triz\Documents\osr2mp4win64\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1041, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "C:\Users\triz\Documents\osr2mp4win64\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 137, in __init__
    self.beatmap_file = get_osu(self.settings.beatmap, self.replay_info.beatmap_hash)
  File "C:\Users\triz\Documents\osr2mp4win64\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Utils\HashBeatmap.py", line 13, in get_osu
    m = osuhash(os.path.join(path, f))
  File "C:\Users\triz\Documents\osr2mp4win64\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Utils\maphash.py", line 6, in osuhash
    with open(filename, 'rb') as b:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/osu!/Songs/984684 Victorious Cast - Take a Hint feat Victoria Justice & Elizabeth Gillies (Speed Up Ver)\\Victorious Cast - Take a Hint feat. Victoria Justice & Elizabeth Gillies (Speed Up Ver.) (SquareTude) [I Think You Could Use a Mint].osu'

**Comment by SenpaiZero** [comment]
same error
