### ISSUE TITLE
PermissionError(13, 'Permission denied')

### ISSUE THREAD

**Issue by KozacheShapka** [uyitroa/osr2mp4-app#118]
PermissionError(13, 'Permission denied')[Errno 13] Permission denied: 'C:/Users/JotaroRokini/AppData/Local/osu!/Songs/865575 Sheet Music Boss - RUSH E' Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 50, in run
    converter = Osr2mp4(filedata=config, filesettings=settings, filepp=ppsettings, logtofile=True, logpath=logpath)
  File "C:\Users\JotaroRokini\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1041, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "C:\Users\JotaroRokini\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 151, in __init__
    self.beatmap = read_file(self.beatmap_file, self.settings.playfieldscale, self.settings.skin_ini.colours, mods=mod_combination, lazy=False)
  File "C:\Users\JotaroRokini\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Parser\osuparser.py", line 516, in read_file
    fiel = open(filename, "r", encoding="utf-8")
PermissionError: [Errno 13] Permission denied: 'C:/Users/JotaroRokini/AppData/Local/osu!/Songs/865575 Sheet Music Boss - RUSH E'

**Comment by Freaky555** [comment]
Do you have a fix?

**Comment by labo-China** [comment]
Try to run it by Administrator

**Comment by SpectrumSX** [comment]
Having also the same issue here
