### ISSUE TITLE
TypeError in Buttons.py

### ISSUE THREAD

**Issue by kas0079** [uyitroa/osr2mp4-app#124]
The program crashes before the GUI appears.
I'm using Python version 3.10.1 on Arch Linux.
I followed the Linux installation guide, so everything in requirements.txt is installed.

> [username@computer osr2mp4-app]$ python main.py 
ERROR:root:FileNotFoundError(2, 'No such file or directory')
ERROR:root:FileNotFoundError(2, 'No such file or directory')
ERROR:root:NoneType: None
 Traceback (most recent call last):
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 364, in <module>
    main()
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 339, in main
    window = Window(App, execpath)
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 75, in __init__
    self.osrbutton = OsrButton(self)
  File "/home/username/Documents/build/osr2mp4-app/HomeComponents/Buttons/OsrButton.py", line 24, in __init__
    super().setup()
  File "/home/username/Documents/build/osr2mp4-app/BaseComponents/Buttons.py", line 46, in setup
    self.setup_shadow()
  File "/home/username/Documents/build/osr2mp4-app/BaseComponents/Buttons.py", line 95, in setup_shadow
    self.shadow.setIconSize(QtCore.QSize(width, height))
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'
NoneType: None
NoneType: None
 Traceback (most recent call last):
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 364, in <module>
    main()
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 339, in main
    window = Window(App, execpath)
  File "/home/username/Documents/build/osr2mp4-app/main.py", line 75, in __init__
    self.osrbutton = OsrButton(self)
  File "/home/username/Documents/build/osr2mp4-app/HomeComponents/Buttons/OsrButton.py", line 24, in __init__
    super().setup()
  File "/home/username/Documents/build/osr2mp4-app/BaseComponents/Buttons.py", line 46, in setup
    self.setup_shadow()
  File "/home/username/Documents/build/osr2mp4-app/BaseComponents/Buttons.py", line 95, in setup_shadow
    self.shadow.setIconSize(QtCore.QSize(width, height))
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'

**Comment by uyitroa** [comment]
I think it's due to the latest python version, try using python3.7 or 3.8

**Comment by kas0079** [comment]
> I think it's due to the latest python version, try using python3.7 or 3.8

I ran it with python 3.7.12 and that fixed it.

**Comment by Stonks3141** [comment]
I had the same problem, might be good to add this to [MacOSLinuxInstall.md](https://github.com/uyitroa/osr2mp4-app/blob/master/MacOSLinuxInstall.md).
