### ISSUE TITLE
M1 macbook module not found "Cython"

### ISSUE THREAD

**Issue by SeanZ7** [uyitroa/osr2mp4-app#127]
When I was installing the application for m1 macbook, i got an error when i reached the step where i was pip installing the required modules. I was thrown this Error

```
ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rc/3jyrny5531s7kxgxp83xn0940000gn/T/pip-install-mmpe8zg_/recordclass/setup.py'"'"'; __file__='"'"'/private/var/folders/rc/3jyrny5531s7kxgxp83xn0940000gn/T/pip-install-mmpe8zg_/recordclass/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rc/3jyrny5531s7kxgxp83xn0940000gn/T/pip-pip-egg-info-_o4jiu_x
         cwd: /private/var/folders/rc/3jyrny5531s7kxgxp83xn0940000gn/T/pip-install-mmpe8zg_/recordclass/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rc/3jyrny5531s7kxgxp83xn0940000gn/T/pip-install-mmpe8zg_/recordclass/setup.py", line 38, in <module>
        from Cython.Distutils import Extension, build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I'm wondering if this is an issue with m1, python3 (i was using pip3 for installations) or something else.

**Comment by uyitroa** [comment]
try python3.7 to avoid rebuilding some libraries

**Comment by SeanZ7** [comment]
I tried 3.7 but that didn't change the error, I ended up installing Cython manually and that seemed to fix it
