### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by localcake** [uyitroa/osr2mp4-app#128]
It says this:

ValueError("invalid literal for int() with base 10: ''")invalid literal for int() with base 10: '' Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 50, in run
    converter = Osr2mp4(filedata=config, filesettings=settings, filepp=ppsettings, logtofile=True, logpath=logpath)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1041, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 120, in __init__
    self.replay_info = parse_replay_file(replaypath)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 181, in parse_replay_file
    return parse_replay(data)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 174, in parse_replay
    return Replay(replay_data)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 44, in __init__
    self.parse_replay_and_initialize_fields(replay_data)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 74, in parse_replay_and_initialize_fields
    self.parse_play_data(replay_data)
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 161, in parse_play_data
    self.play_data = [ReplayEvent(int(event[0]), float(event[1]), float(event[2]), int(event[3])) for event in events]
  File "C:\Users\Thando\Desktop\osu2r\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osrparse\replay.py", line 161, in <listcomp>
    self.play_data = [ReplayEvent(int(event[0]), float(event[1]), float(event[2]), int(event[3])) for event in events]
ValueError: invalid literal for int() with base 10: ''

**Comment by reinacchi** [comment]
I tried converting one of my replays from the Lazer client and received the same error too.
