### ISSUE TITLE
Error when trying to run [Mac]

### ISSUE THREAD

**Issue by TheAvacad0** [uyitroa/osr2mp4-app#139]
After following the install instructions for mac, i get a terminal error after trying to run it
**This is what I Typed 'python3 main.py'** I Installed all the missing modules and i get this:
```
ERROR:root:FileNotFoundError(2, 'No such file or directory')
ERROR:root:FileNotFoundError(2, 'No such file or directory')
ERROR:root:NoneType: None
 Traceback (most recent call last):
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 364, in <module>
    main()
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 339, in main
    window = Window(App, execpath)
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 75, in __init__
    self.osrbutton = OsrButton(self)
  File "/Users/myusername/BrewApps/osr2mp4-app/HomeComponents/Buttons/OsrButton.py", line 24, in __init__
    super().setup()
  File "/Users/myusername/BrewApps/osr2mp4-app/BaseComponents/Buttons.py", line 46, in setup
    self.setup_shadow()
  File "/Users/myusername/BrewApps/osr2mp4-app/BaseComponents/Buttons.py", line 95, in setup_shadow
    self.shadow.setIconSize(QtCore.QSize(width, height))
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'
NoneType: None
NoneType: None
 Traceback (most recent call last):
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 364, in <module>
    main()
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 339, in main
    window = Window(App, execpath)
  File "/Users/myusername/BrewApps/osr2mp4-app/main.py", line 75, in __init__
    self.osrbutton = OsrButton(self)
  File "/Users/myusername/BrewApps/osr2mp4-app/HomeComponents/Buttons/OsrButton.py", line 24, in __init__
    super().setup()
  File "/Users/myusername/BrewApps/osr2mp4-app/BaseComponents/Buttons.py", line 46, in setup
    self.setup_shadow()
  File "/Users/myusername/BrewApps/osr2mp4-app/BaseComponents/Buttons.py", line 95, in setup_shadow
    self.shadow.setIconSize(QtCore.QSize(width, height))
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'
```
How do i fix this? (I'm Running MacOS Monterey 12.4 on an Intel MacBook Pro)

**Comment by TheAvacad0** [comment]
Pillow-SIMD also won't work, so i tried Pillow
