### ISSUE TITLE
CalledProcessError(1, ['ffmpeg', '-i', 'libs ----- (it sorted it self out some how???? it threw the error once then it worked after i reloaded it...)

### ISSUE THREAD

**Issue by blackcat1101** [uyitroa/osr2mp4-app#143]
im getting this error when trying to make a video from a decently long replay file. 
(it sorted it self out some how???? it threw the error once then it worked after i reloaded it...)

CalledProcessError(1, ['ffmpeg', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/outputf.avi', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/audio.mp3', '-c:v', 'copy', '-c:a', 'aac', '-ab', '500k', 'C:/Users/bayle/Videos/replay to mp4/603738 SakiZ osu favourites played by BassBoostedDuck.avi', '-y'])Command '['ffmpeg', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/outputf.avi', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/audio.mp3', '-c:v', 'copy', '-c:a', 'aac', '-ab', '500k', 'C:/Users/bayle/Videos/replay to mp4/603738 SakiZ osu favourites played by BassBoostedDuck.avi', '-y']' returned non-zero exit status 1. Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 80, in run
    converter.joinall()
  File "C:\Users\bayle\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1039, in autologging_traced_instancemethod_delegator
    return proxy(method, args, keywords)
  File "C:\Users\bayle\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1196, in __call__
    value = function(*args, **keywords)
  File "C:\Users\bayle\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 242, in joinall
    mix_video_audio(self.settings)
  File "C:\Users\bayle\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\VideoProcess\DiskUtils.py", line 34, in mix_video_audio
    subprocess.check_call([settings.ffmpeg, '-i', f, '-i', settings.temp + 'audio.mp3', '-c:v', 'copy', '-c:a', settings.audiocodec, '-ab', str(settings.settings["Audio bitrate"]) + "k", settings.output, '-y'], stdout=stream, stderr=stream)
  File "C:\Users\bayle\Desktop\osr2mp4\libs\pythonlib\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/outputf.avi', '-i', 'libs\\pythonlib\\lib\\site-packages\\osr2mp4/9b704bc6-826a-11ed-860e-001a7dda7115temp/audio.mp3', '-c:v', 'copy', '-c:a', 'aac', '-ab', '500k', 'C:/Users/bayle/Videos/replay to mp4/603738 SakiZ osu favourites played by BassBoostedDuck.avi', '-y']' returned non-zero exit status 1.

**Comment by blackcat1101** [comment]
it sorted it self out, all i did was change the settings to 1080 height and 1920 width... that sorted it for some reason... idk.
