### ISSUE TITLE
error "Source contains parsing errors: "

### ISSUE THREAD

**Issue by ssebastianoo** [uyitroa/osr2mp4-app#73]
When I try to convert a map this happens ![bug](https://elon-musk.is-inside.me/dDfcZONk.png)

**Comment by ssebastianoo** [comment]
```
Source contains parsing errors: '<string>'
	[line 37]: '#[Credits]#\n'Source contains parsing errors: '<string>'
	[line 37]: '#[Credits]#\n' Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 50, in run
    converter = Osr2mp4(filedata=config, filesettings=settings, filepp=ppsettings, logtofile=True, logpath=logpath)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1041, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 135, in __init__
    setupglobals(self.data, gameplaysettings, self.replay_info.mod_combination, self.settings, ppsettings=ppsettings)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 797, in autologging_traced_function_delegator
    return proxy(function, args, keywords)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1196, in __call__
    value = function(*args, **keywords)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Utils\Setup.py", line 54, in setupglobals
    skin = Skin(skin_path, default_path)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Parser\skinparser.py", line 96, in __init__
    self.read()
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Parser\skinparser.py", line 131, in read
    config.read_string(lines)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\configparser.py", line 722, in read_string
    self.read_file(sfile, source)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "C:\Users\mediaworld\Desktop\osr2mp4\libs\pythonlib\lib\configparser.py", line 1110, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '<string>'
	[line 37]: '#[Credits]#\n'

```

**Comment by ssebastianoo** [comment]
I changed the skin and it's working, but why?

**Comment by ssebastianoo** [comment]
[this](https://www.youtube.com/watch?v=Q22Y_5q78e8&t=45s) was the skin
